package myapp.com.karry.modules

import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import myapp.com.karry.entity.City

class MyViewModel(private val cityMutableList: MutableLiveData<List<City>>) : ViewModel() {
    private val cityLisArray: ArrayList<City> = arrayListOf()




    private fun createCityList() {
            cityLisArray.add(City("Paris"))
            cityLisArray.add(City("Londres"))
            cityLisArray.add(City("Tokyo"))
            cityLisArray.add(City("Bangkok"))
            cityLisArray.add(City("New York"))
            cityLisArray.add(City("Dublin"))
            cityLisArray.add(City("Sydney"))
            cityLisArray.add(City("Prague"))
            cityLisArray.add(City("Stockholm"))
            cityLisArray.add(City("Rio de Janeiro"))
            cityLisArray.add(City("Brasilia"))
            cityLisArray.add(City("Mexico"))
            cityLisArray.add(City("Los Angeles"))
            cityLisArray.add(City("Montreal"))
            cityLisArray.add(City("Chicoutimi"))
            cityLisArray.add(City("Madrid"))
            cityLisArray.add(City("Rome"))
            cityLisArray.add(City("La Valette"))
            cityLisArray.add(City("Marseille"))
            cityLisArray.add(City("Lille"))
            cityLisArray.add(City("Nantes"))
            cityLisArray.add(City("Rouen"))
            cityLisArray.add(City("Tour"))
            cityLisArray.add(City("Amsterdam"))
            cityLisArray.add(City("Berlin"))
            cityLisArray.add(City("Bobigny"))
            cityLisArray.add(City("Montreuil"))
            cityLisArray.add(City("Lima"))
            cityLisArray.add(City("Franckfort"))
            cityLisArray.add(City("Barcelone"))
            cityLisArray.add(City("Rabat"))
            cityLisArray.add(City("Casablanca"))
            cityLisArray.add(City("La Paz"))
            cityLisArray.add(City("Marracech"))
            cityLisArray.add(City("Chicago"))
            cityLisArray.add(City("Torronto"))
            cityLisArray.add(City("Sophia"))
            cityLisArray.add(City("Lisbonne"))
            cityLisArray.add(City("Tanger"))
            cityLisArray.add(City("Cardif"))
            cityLisArray.add(City("Séoul"))
            cityLisArray.add(City("Lagos"))
            cityLisArray.add(City("Niameu"))
            cityLisArray.add(City("Bamako"))
            cityLisArray.add(City("Johanesbourd"))
            cityLisArray.add(City("Monovia"))
            cityLisArray.add(City("Moscou"))
            cityLisArray.add(City("Libreville"))
            cityLisArray.add(City("Nerobi"))
            cityLisArray.add(City("Tunis"))
            cityLisArray.add(City("Alger"))
            cityLisArray.add(City("Le Caire"))
            cityLisArray.add(City("Beyrouth"))
            cityLisArray.add(City("Istanbul"))
            cityLisArray.add(City("Ankarra"))
            cityLisArray.add(City("Athenes"))
            cityLisArray.add(City("Bukarest"))
            cityLisArray.add(City("Zabreg"))
            cityLisArray.add(City("Vienne"))
            cityLisArray.add(City("Kiev"))
            cityLisArray.add(City("New Delhi"))
            cityLisArray.add(City("Katmandou"))
            cityLisArray.add(City("Hanoï"))
            cityLisArray.add(City("Pékin"))
            cityLisArray.add(City("Quimper"))
            cityLisArray.add(City("Shangaï"))
            cityLisArray.add(City("Luxembourg"))
            cityLisArray.add(City("Jakarta"))
            cityLisArray.add(City("Dubaï"))
    }

}